### ISSUE TITLE
QL-550 - command example

### ISSUE THREAD

**Issue by maki3000** [philpem/printer-driver-ptouch#17]
Hello,

I successfully installed this printer driver on my Raspberry Pi Noobs OS.

Now I'd like to print an image on my QL-550 on a 62mm endless roll with following command:
```
lp -d Brother_P-Touch image.png
```
The green light of my printer starts to blink, but furthermore nothing happens. I guess, my cmd is wrong. Maybe I need to specify the size or take another image than PNG. I don't know.

There is no error feedback in my terminal thrown.

Could somebody please give me an example of how this cmd could look like?

**Comment by philpem** [comment]
I've never directly sent data to the P-touch driver using lp, but you'll need to get the printing options (notably the page width and label type (continuous or cut-feed) correct, otherwise the printer will reject the image data. I don't know how to pass these into lp -- you'll have to consult the manpages and possibly the CUPS documentation.

Sending a PNG file directly to the printer is not likely to work -- though if you can convert it into a PDF, it should.

Bear in mind that the page on the P-touch printers is rotated 90 degrees. That means the width of your page should be 62mm, and the height is the length of the label you wish to print.

**Comment by philpem** [comment]
Closed due to being inactive for nearly a year with no response from submitter
